- name: Install the package "git-core"
  become: true
  apt:
    name: git-core
    state: present

- name: Install Java
  become: true
  apt:
    name: openjdk-11-jre
    state: present

- name: Install the package "wiringpi"
  become: true
  apt:
    name: wiringpi
    state: present